name: "resnet_preprocessing"
backend: "python"
max_batch_size: 4


input [
  {
    name: "IMAGE_PATH"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "IMAGE_FP32"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  },
  {
    name: "IMAGE_FP16"
    data_type: TYPE_FP16
    dims: [ 3, 224, 224 ]
  }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]

parameters: [
  {
    key: "EXECUTION_ENV_PATH"
    value: {
      string_value: "$$TRITON_MODEL_DIRECTORY/triton_cv_env310.tar.gz"
    }
  }
]
